### ISSUE TITLE
ImportError: DLL load failed while importing _loess

### ISSUE THREAD

**Issue by pohndorff** [has2k1/scikit-misc#12]
Hi,

I have `scikit-misc 0.1.4` installed in an Anaconda environment on Windows 10.
When I try to import `skmisc.loess.loess` i receive the following error:

```
>>> from skmisc.loess import loess
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Tools\Anaconda\lib\site-packages\skmisc\loess\__init__.py", line 51, in <module>
    from ._loess import (loess, loess_model, loess_inputs, loess_control,
ImportError: DLL load failed while importing _loess: Das angegebene Modul wurde nicht gefunden.
```
Same error with version 0.1.3.

Is that error related to issue #4?

**Comment by mdancho84** [comment]
Hey @has2k1 awesome package. I'm an instructor and founder of a company called Business Science, and I'm teaching your `plotnine` package in my 101 course for Python Data Science Automation. @pohndorff is one of my students, and I'm trying to assist him with troubleshooting. 

Have you seen this issue before with DLL failing?

In the course, we are using:

```
name: ds4b_101p
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.1
  - pip
  - pip:
      # Core Data
      - numpy==1.20.2
      - pandas==1.2.2

      # R Data
      - plydata==0.4.3
      - siuba==0.0.24
      - datatable

      # Visualization
      - matplotlib==3.3.4
      - plotnine==0.7.1
      - mizani==0.7.2
      - plotly==4.14.3
      - altair==4.1.0

      # EDA
      - pandas-profiling
      - ppscore==1.2.0
      - pyjanitor==0.20.14

      # Modeling & Machine Learning
      - statsmodels
      - nltk==3.5
      - h2o==3.32.0.3
      - pycaret==2.3.0
      - scikit-learn==0.23.2
      - xgboost==0.90
      - lightgbm==3.1.1
      - catboost==0.24.4
      - sklearn-pandas==2.0.4
      - scikit-misc==0.1.3

      # Time Series
      - sktime==0.5.3
      - pmdarima==1.8.1
      - tsfresh==0.17.0

      # Scalability & Automation
      - dask==2.30.0
      - dask-ml==1.8.0
      - dask-xgboost==0.1.11
      - zict==1.0.0
      - joblib==1.0.1

      # API
      - fastapi==0.63.0
      - uvicorn==0.13.4

      # Database
      - sqlalchemy==1.4.7

      # Excel
      - xlsxwriter==1.3.7
      - openpyxl

      # Jupyter
      - jupyterlab==3.0.13
      - jupyterlab-server==2.4.0
      - jupyter-packaging==0.7.12
      - jupyter-server==1.6.1 # Solves ImportError: cannot import name 'get_version_info' from 'jupyter_packaging'
      - ipywidgets==7.6.3
      - ipympl==0.7.0
      - jupytext
      - papermill==2.3.3

      # Apps
      - streamlit==0.80.0

      # Terminal Formatting
      - rich

      # Extending Pandas
      - pandas_flavor

      # R users
      - radian
      - jedi==0.17.2
  

```

**Comment by has2k1** [comment]
As I do not use windows and have no access to a suitable windows system I cannot attempt to reproduce this failure.

But, my guess is that you need to install [numpy+mkl](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy).

**Comment by xie186** [comment]
> Hi,
> 
> I have `scikit-misc 0.1.4` installed in an Anaconda environment on Windows 10. When I try to import `skmisc.loess.loess` i receive the following error:
> 
> ```
> >>> from skmisc.loess import loess
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "D:\Tools\Anaconda\lib\site-packages\skmisc\loess\__init__.py", line 51, in <module>
>     from ._loess import (loess, loess_model, loess_inputs, loess_control,
> ImportError: DLL load failed while importing _loess: Das angegebene Modul wurde nicht gefunden.
> ```
> 
> Same error with version 0.1.3.
> 
> Is that error related to issue #4?

Did you resolve this problem? If yes, how did you do it? Thanks in advance!

**Comment by jay9044** [comment]
Still facing this issue also

**Comment by alcs417** [comment]
Same here, After installed numpy+mkl, the issue still exists. Does anyone know how to fix the problem? I have spent over 10 hours trying to solve the problem but made no progress at all. Any possible solutions will be much appreciated.

**Comment by mdancho84** [comment]
I have been unable to reproduce this issue but have heard of one possible solution:

Move scikit-misc above pandas in the yaml so it gets installed first. 

Let me know if this works.

**Comment by alcs417** [comment]
> I have been unable to reproduce this issue but have heard of one possible solution:
> 
> Move scikit-misc above pandas in the yaml so it gets installed first.
> 
> Let me know if this works.

Hi, thanks for your help and sadly, it did not work either.
I have installed the scikit-misc package on three PCs, i.e. Win 7 64 bit, Win 10 64 bit and Ubuntu 18.04, all equipped with Python 3.7.9.  Only the Ubuntu one runs fluently, while the other two Windows machines all have this problem. It really drove my crazy.... Anyway, thanks again and I might just need to stick with Ubuntu for debugging my program.

**Comment by Jabbar-Campbell** [comment]
> Hi,
> 
> I have `scikit-misc 0.1.4` installed in an Anaconda environment on Windows 10. When I try to import `skmisc.loess.loess` i receive the following error:
> 
> ```
> >>> from skmisc.loess import loess
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "D:\Tools\Anaconda\lib\site-packages\skmisc\loess\__init__.py", line 51, in <module>
>     from ._loess import (loess, loess_model, loess_inputs, loess_control,
> ImportError: DLL load failed while importing _loess: Das angegebene Modul wurde nicht gefunden.
> ```
> 
> Same error with version 0.1.3.
> 
> Is that error related to issue #4?

I'm having this issue and have been unsuccessful in getting past this. Did you ever find a solution to this problem?

**Comment by djaustin1** [comment]
Same issue!  Windows 11 x64.

**Comment by AJZw** [comment]
Hi all,

I found the culprit and a work-around.
My setup: Window 10x64; a non-(ana)conda python virtual environment; `scikit-misc==0.1.4`.
`scikit-misc.loess` requires MKL as previous mentioned by has2k1. I used intel's version of numpy+MKL: `intel-numpy`. (Of note: I had to manually specify the mkl dll directory for `intel-numpy` to avoid even more dll import errors, see: `os.add_dll_directory()`).

Even with numpy+MKL the '_loess' dll load failure persists. Upon further inspection of `_loess.cp38-win_amd64.pyd` with Dependencies, two DLL's were unfindable: `mkl_rt.dll` & `libmmd.dll`. Crossreferencing these DLL's with my MKL DLL directory located both, but showed that `mkl_rt.dll` was actually named `mkl_rt.2.dll`. The quick work-around is to duplicate `mkl_rt.2.dll` and rename it to `mkl_rt.dll`, which fixes the DLL load failure.

Hope this helps!

**Comment by jancgreyling** [comment]
Where can I find the mkl_rt.2.dll file?

**Comment by AJZw** [comment]
The dll should be included in `intel-numpy`, the exact directory depends on your setup.

In my case: `.\the-virtual-environment-folder\Library\bin\mkl_rt.2.dll`

**Comment by jancgreyling** [comment]
Thanks but I could not find it - hopefully the maintainer of scikit-misc will be able to solve the issue - I teach at a University and want to use the package but I cannot have 25 students rummaging through their files to find this dll file. Being in Africa most of our students use Windows systems.

**Comment by has2k1** [comment]
> Thanks but I could not find it - hopefully the maintainer of scikit-misc will be able to solve the issue - I teach at a University and want to use the package but I cannot have 25 students rummaging through their files to find this dll file. Being in Africa most of our students use Windows systems.

Given the make up (fortran, c, cython and python) of the codebase, making builds that are easy to install is hard. It is even harder for Windows systems. I plan to migrate to a new build system (meson) that should (hopefully) make this process easier. I am also in Africa :) and I know the tech environment.

**Comment by jancgreyling** [comment]
Much appreciated [has2k1](https://github.com/has2k1)!

**Comment by has2k1** [comment]
@jancgreyling, I have moved `scikit-misc` to a new build-system and I have a test release.
Please try installing the release-candidate and let me know how it works out.

```sh
pip install -i https://test.pypi.org/simple/ "scikit-misc==0.2.0rc1"
```

**Comment by AJZw** [comment]
@has2k1 I gave it a quick test too. I fitted the loess smoother to some random data in a fresh environment with the default (so without MKL) numpy. The script ran great without any (import) problems. 

Thanks!

**Comment by has2k1** [comment]
@AJZw, thank you very much. I guess that is it. Finally!

**Comment by jancgreyling** [comment]
Hallo Hassan,

well done on the implementation and keeping us in the loop!

With appreciation,

Jan

From: Hassan Kibirige ***@***.***>
Date: Saturday, 04 March 2023 at 18:17
To: has2k1/scikit-misc ***@***.***>
Cc: Greyling, Jan C, Dr ***@***.*** ***@***.***>, Mention ***@***.***>
Subject: Re: [has2k1/scikit-misc] ImportError: DLL load failed while importing _loess (#12)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
CAUTION: This email originated from outside the Stellenbosch University network. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@AJZw<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAJZw&data=05%7C01%7C%7Ca1500793a4064015389408db1ccc0078%7Ca6fa3b030a3c42588433a120dffcd348%7C0%7C0%7C638135434756260449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gXvTF6IG3yfDEjQvy%2F%2BXiCqeS%2FDCOjZqkVwKrAwCF98%3D&reserved=0>, thank you very much. I guess that is it. Finally!

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhas2k1%2Fscikit-misc%2Fissues%2F12%23issuecomment-1454791209&data=05%7C01%7C%7Ca1500793a4064015389408db1ccc0078%7Ca6fa3b030a3c42588433a120dffcd348%7C0%7C0%7C638135434756260449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pqpcKjihmLy7FA7CbhcLoj%2BuIAiFmagmHX8H4XW4GeU%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO36RYBOLK3XHRQSVB4XDL3W2NTK3ANCNFSM46BFDWRQ&data=05%7C01%7C%7Ca1500793a4064015389408db1ccc0078%7Ca6fa3b030a3c42588433a120dffcd348%7C0%7C0%7C638135434756260449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yrOBq8D3dvr0fqhAQDOFlxkP8Yjvfeu8qGHmhqC9k2k%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

The integrity and confidentiality of this email are governed by these terms. Disclaimer<https://www.sun.ac.za/emaildisclaimer/default.aspx>
Die integriteit en vertroulikheid van hierdie e-pos word deur die volgende bepalings bereël. Vrywaringsklousule<https://www.sun.ac.za/emaildisclaimer/default.aspx>
