### ISSUE TITLE
svddc failed in l2fit

### ISSUE THREAD

**Issue by XDynames** [has2k1/scikit-misc#9]
Just wondering if you have any advice - maybe I am trying to use the library incorrectly.

I am trying to fit and predict on a ~28,000x4 training set of x-values
I followed the advice of a previous issue that required adding `surface='direct'` - not sure if this is really what I want to do, but it did get rid of the `Extrapolation not allowed with blending` error. As a point of clarification by having the weights am I blending?

Anyway since this change I now receive `svddc failed in l2fit.` I followed this trace back to loessf.f line 379 but I can't really understand the code well enough to figure out why that trigger is activating - other than its a problem with SVD. For context here is how I am calling loess:
```
def fit(x, y, bandwidth):
    weights = tricubic_kernel(x, bandwidth)
    for i in range(len(y)):
        model = loess(x, y, weights[:,i], surface='direct', degree=1.fit()  
```

**Comment by XDynames** [comment]
Fitting with a subset of the data seems to remedy this - any advice?

**Comment by has2k1** [comment]
You are doing it right, the problem is the data. Somewhere along the way, the loess algorithm fails to decompose the data. 
The the underlying loess algorithm uses various "tricks" (more complex datastructures & algorithms) for performance, but that makes the it trip up for some types of data.

So, it is not the case that your data cannot be loess smoothed, but that it cannot pass all the assumptions for this algorithm.

**Comment by XDynames** [comment]
Yes I found a NaN floating around still - that allows it to progress a little. However I now get `There are other near singularities as well. 89.264\n` The number displayed at the end changes as the span is varied but doesn't seem to fix the problem. Still seems related to the SVD code. Any pointers?

**Comment by has2k1** [comment]
The data is still the source of the problems and yes it is still related to the SVD code.

1. `svddc failed in l2fit` error - Means there is no "reasonable" variation in the predictor variable for some spanned region. An extreme example is if `x = [1, 1, 1, ... 1], y = [...]`
2. `There are other near singularities as well.` error - Means there isn't enough *qualitative* data in a spanned region to compute a meaningful regression. This error is kind of a lesser version of the previous one. For example if `x = [0, 0, 1, 1, 2, 2, 3, 3], y = [0, 1, 1, 2, 2, 3, 3, 4]`, there are two values for the same predictor variable and if the span is small you will get singularities or near singularities.

For both errors a possible solution is to increase the span so that the operations on the matrix have enough meaningful variation to succeed, but this may not work. Another solution (to be used with precaution) is to introduce a "jitter" in the predictor variable to break any singularities. The trick is to start with the smallest amount of jitter and work your way down to one that works e.g. `1e-16, 1e-14, 1e-15...` , making sure that it is a tiny proportion of the smallest value (absolute) of the predictor variable. 

Sometimes you may have to increase the span a little just so that the jitter may remain small! It can be finicky if the data is really pathological.

```python
from skmisc.loess import loess
import numpy as np

n = 10
x = np.ones(n)
y = x
model = loess(x, y, span=.35, degree=1).fit() # Fails, ValueError: b'svddc failed in l2fit.'

x = np.array([i//2 for i in range(n)])
y = [x//2 + 1 if x%2 else x//2 for x in range(n)]
model = loess(x, y, span=.35, degree=1).fit() # Fails, ValueError: b'There are other near singularities as well. 1\n'

# Possible solution: Increase the span
model = loess(x, y, span=.5, degree=1).fit()  # Fails, ValueError: b'There are other near singularities as well. 1\n'
model = loess(x, y, span=.6, degree=1).fit()  # Succeeds


# Possible solution: Add a jitter to the predictor variable (x)
amount = 1e-13
x = np.array([i//2 for i in range(n)])
y = [x//2 + 1 if x%2 else x//2 for x in range(n)]
np.random.seed(1234)
jitter = np.random.uniform(-amount, amount, n)
model = loess(x+jitter, y, span=.35, degree=1).fit()
```

Finally, here you can see the difference between the two errors.
```python
n = 10
x = [i//3 + 1 if i%3 else i//3 for i in range(1, n+1)] # [1, 1, 1, 2, 2, 2, 3, 3, 3, 4]
y = np.arange(n)
# .3 span will select [1, 1, 1] for a local regression -- singularity (total failure)
model = loess(x, y, span=.3, degree=1).fit() # Fails, ValueError: b'svddc failed in l2fit.'

# .4 span will select [1, 1, 1, 2]  for a local regression -- near singularity
model = loess(x, y, span=.4, degree=1).fit() # Fails, ValueError: b'There are other near singularities as well. 1\n'
```

**Comment by XDynames** [comment]
Hmmm this is concerning as I already had the span turned up to 1 and it didn't help.

Thank you for all your help - I think I have sufficient intuition to probe this dataset a little more

Just as an update the issue was my tricubic kernel's bandwidth, too low and it would trigger the singularity warning
